---
version: '3.7'
services:
  cassandra-node1-cdc0:
    image: cassandra:4.0
    hostname: cassandra-node1-cdc0
    container_name: cassandra-node1-cdc0
    environment:
      CASSANDRA_DC: dc2
      CASSANDRA_RACK: rack1
      CASSANDRA_SEEDS: cassandra-node1-cdc0,cassandra-node1-cdc1 
      CASSANDRA_ENDPOINT_SNITCH: org.apache.cassandra.locator.GossipingPropertyFileSnitch
      CASSANDRA_CLUSTER_NAME: my_cluster
      # JVM_OPTS: "-Dcom.sun.management.jmxremote.port=9050 -Dcom.sun.management.jmxremote.rmi.port=9050 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=192.168.68.52"
    volumes:
      - ./conf/etc/cassandra/cassandra-dc0.yaml:/etc/cassandra/cassandra.yaml:rw
    ports:
      - "0.0.0.0:9042:9042"
      # - "0.0.0.0:9050:9050"
    entrypoint:
      - bash
      - -c
      - |
        /usr/local/bin/docker-entrypoint.sh
  cassandra-node1-cdc1:
    image: cassandra:4.0
    hostname: cassandra-node1-cdc1
    container_name: cassandra-node1-cdc1
    environment:
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_SEEDS: cassandra-node1-cdc0,cassandra-node1-cdc1
      CASSANDRA_ENDPOINT_SNITCH: org.apache.cassandra.locator.GossipingPropertyFileSnitch
      CASSANDRA_CLUSTER_NAME: my_cluster
      # JVM_OPTS: "-Dcom.sun.management.jmxremote.port=9050 -Dcom.sun.management.jmxremote.rmi.port=9050 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=192.168.68.52"
    volumes:
      - ./conf/etc/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml:rw
      - ./conf/etc/cassandra/cassandra-debezium.yaml:/etc/cassandra/cassandra-debezium.yaml:rw
      - ./conf/etc/debezium/cdc.properties:/etc/debezium/cdc.properties:rw
      - ./deps/binaries/debezium-connector-cassandra-4-2.5.0.Final-jar-with-dependencies.jar:/debezium-connector-cassandra-4-2.5.0.Final-jar-with-dependencies.jar:rw
    entrypoint:
      - bash
      - -c
      - |
        /usr/local/bin/docker-entrypoint.sh
  kafka2:
    image: confluentinc/cp-kafka
    container_name: kafka2
    hostname: kafka2
    ports:
      - "0.0.0.0:9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka2:29092,CONTROLLER://kafka2:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka2:29092,EXTERNAL://192.168.68.52:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka2:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
  prometheus:
    image: prom/prometheus:v2.43.0
    hostname: prometheus
    ports:
      - 0.0.0.0:9090:9090
    volumes:
      - ./conf/etc/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:9.4.7
    environment:
      GF_PATHS_DATA: /var/lib/grafana
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - ./conf/etc/grafana/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./conf/etc/grafana/provisioning.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./conf/etc/grafana/dashboards:/var/lib/grafana/dashboards
