apiVersion: 1

providers:
  - name: 'CDC Notifications Experiment'
    orgId: 1
    folder: 'General'
    folderUid: ''
    type: file
    disableDeletion: true
    updateIntervalSeconds: 10
    allowUiUpdates: false
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: true
