global:
  scrape_interval: 10s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels: {}

scrape_configs:
  - job_name: consumer
    honor_labels: true
    metrics_path: /metrics
    scheme: http

    static_configs:
      - targets: ["192.168.68.52:12400"]
        labels:
          service: stress_runner
